name: CI Pipeline

# Trigger the pipeline on push and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # The environment to run the job on (can be ubuntu, macos, windows)

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java 21 (using Temurin from Adoptium)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build the project using Maven (adjust if using Gradle or another tool)
      - name: Build with Maven
        run: mvn clean install

      - name: Verify Jar File
        run: ls -l target
      # Run tests
      - name: Run tests
        run: mvn test



  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/book-api:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/book-api:latest


